spring:
  datasource:
    url: ""
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

ssh:
  url: ""
  port: 22
  username: ""
  password: ""
  targetHost: ""
  targetPort: 5432